import Head from "next/head";

import { Navigation } from "../components/Navigation";
import { SkipLink } from "../components/SkipLink";
import "../styles/globals.scss";
import "../styles/reset.scss";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Jefferson Bledsoe</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
        <a rel="me" href="https://fosstodon.org/@JeffersonBledsoe">Mastodon</a>
      </Head>
      <SkipLink />
      <Navigation />
      <main id="main-content">
        <Component {...pageProps} />
      </main>
    </>
  );
}

export default MyApp;
