import Head from "next/head";
import Script from "next/script";
import { Navigation } from "../components/Navigation";
import { SkipLink } from "../components/SkipLink";
import "../styles/globals.scss";
import "../styles/reset.scss";

function MyApp({ Component, pageProps }) {
  return (
    <>
      {process.env.NODE_ENV === "production" ? (
        <Script
          strategy="lazyOnload"
          src="https://beampipe.io/js/tracker.js"
          data-beampipe-domain="jeffersonbledsoe.com"
        />
      ) : null}
      <Head>
        <title>Jefferson Bledsoe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SkipLink />
      <Navigation />
      <main id="main-content">
        <Component {...pageProps} />
      </main>
    </>
  );
}

export default MyApp;
