import { PageConfig } from "next";
import Head from "next/head";
import Link from "next/link";
import { ContactList } from "../components/ContactList";
import { Navigation } from "../components/Navigation";
import { SkipLink } from "../components/SkipLink";

// Todo: Automatically get current year for footer
// Todo: Add icons for social footers
// Todo: Add visually hidden classes to the sections to make navigation via screen reader easier
// Todo: Add descriptions to projects
// Todo: Add descriptions and links to side projects

const ProjectCard = ({ title, description, link }) => {
  return (
    <>
      <h3>
        <Link href={link}>{title}</Link>
      </h3>
      <p>{description}</p>
    </>
  );
};

const IntroHero = () => {
  return (
    <>
      <span style={{ fontSize: "1.5rem" }}>Hi 👋 I&apos;m</span>
      <h1
        style={{
          fontFamily: "Playfair Display",
          fontWeight: 800,
          fontSize: "4rem",
          marginBlockStart: "0",
        }}
      >
        Jefferson Bledsoe
      </h1>
    </>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Jefferson Bledsoe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SkipLink />

      <Navigation />

      <main id="main-content">
        <IntroHero />
        <section id="introduction">
          <p>
            I&apos;m a software developer based in Birmingham, UK. I&apos;m
            currently working in a remote-hybrid full-stack software developer
            role at <Link href="https://www.pretagov.co.uk/">PretaGov</Link>. I
            love working on web frontend, with a focus on building inclusive and
            accessible services with their users at the core. I&apos;ve worked
            on desktop music applications in the past and enjoy experimenting
            with tech in my free time. Feel free to see my work or get in touch!
          </p>
          <ContactList style={{ marginBlock: "5rem" }} />
          {/* <ul role="list">
            <li>
              <Link href="mailto:me@jeffersonbledsoe.com">Mail</Link>
            </li>
            <li>
              <Link href="https://twitter.com/jeff_bledsoe">Twitter</Link>
            </li>
            <li>
              <Link href="https://github.com/JeffersonBledsoe">Twitter</Link>
            </li>
            <li>
              <Link href="https://www.linkedin.com/in/jeffersonbledsoe/">
                LinkedIn
              </Link>
            </li>
          </ul> */}
        </section>
        {/* <section id="projects">
          <h2>Projects</h2>
          <ul>
            <li>
              <ProjectCard
                title="Land Registry 1862 Digital Archives"
                description=""
                link="http://digitalarchives.landregistry.gov.uk"
              />
            </li>
            <li>
              <ProjectCard
                title="PretaForm"
                description=""
                link="https://pretaform.com/"
              />
            </li>
          </ul>
        </section>
        <section id="side-projects-and-hobbies">
          <h2>Side projects and hobbies</h2>
          <ul>
            <li>
              <ProjectCard title="Home automation" description="" link="#" />
            </li>
            <li>
              <ProjectCard title="Home networking" description="" link="#" />
            </li>
          </ul>
        </section> */}
      </main>
      {/* <footer
        style={{
          borderTop: "1px solid black",
          backgroundColor: "rgb(38, 38, 38)",
        }}
      >
        <p>&copy; 2021 Jefferson Bledsoe</p>
        <ContactList />
      </footer> */}
    </>
  );
}

export const config: PageConfig = {
  unstable_runtimeJS: false,
};
