import { PageConfig } from "next";
import Head from "next/head";
import Link from "next/link";
import { ContactList } from "../components/ContactList";
import { IntroHero } from "../components/IntroHero";

// Todo: Automatically get current year for footer
// Todo: Add icons for social footers
// Todo: Add visually hidden classes to the sections to make navigation via screen reader easier
// Todo: Add descriptions to projects
// Todo: Add descriptions and links to side projects

export default function Home() {
  return (
    <>
      <Head>
        <title>Jefferson Bledsoe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IntroHero text="Jefferson Bledsoe" subtext="Hi 👋 I'm" />
      <section id="introduction">
        <p>
          I&apos;m a software developer based in Birmingham, UK. I&apos;m
          currently working in a remote-hybrid full-stack software developer
          role at <Link href="https://www.pretagov.co.uk/">PretaGov</Link>. I
          love working on web frontend, with a focus on building inclusive and
          accessible services with their users at the core. I&apos;ve worked on
          desktop music applications in the past and enjoy experimenting with
          tech in my free time. Feel free to see my work or get in touch!
        </p>
        <ContactList style={{ marginBlock: "5rem" }} />
      </section>
    </>
  );
}

export const config: PageConfig = {
  unstable_runtimeJS: false,
};
